name: Icarus Verilog CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Icarus
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Compile
        run: iverilog -Wall -o sim.vvp src/*.v tb/tb.v

      - name: Run
        run: vvp sim.vvp