name: Verilog CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   coverage:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Install Icarus + Covered
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog covered

      - name: Compile with VCD Dump
        run: |
          iverilog -Wall -o sim.vvp -D DUMP_VCD src/*.v tb/tb.v

      - name: Run Simulation + Generate Coverage
        run: |
          vvp sim.vvp
          covered score -t tb -vcd dump.vcd -o coverage.cdd
          covered report coverage.cdd > coverage_report.txt
          cat coverage_report.txt

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report.txt